### ISSUE TITLE
Crashed when completionBlock passed as argument

### ISSUE THREAD

**Issue by SpectralDragon** [mhdhejazi/Dynamic#1]
I wanna call method `beginSheetModalForWindow:completionHandler:` in NSOpenPanel object, but app crashed in `Invocation.swift` file at line 139.

How to pass object?

**Comment by mhdhejazi** [comment]
It would be great if you post a complete example so I can reproduce the issue.

**Comment by SpectralDragon** [comment]
```swift

extension UIWindow {
    var nsWindow: AnyObject? {
        guard let nsWindows = NSClassFromString("NSApplication")?.value(forKeyPath: "sharedApplication.windows") as? [AnyObject] else { return nil }
        for nsWindow in nsWindows {
            let uiWindows = nsWindow.value(forKeyPath: "uiWindows") as? [UIWindow] ?? []
            if uiWindows.contains(self) { return nsWindow }
        }
        return nil
    }
}

let panel = Dynamic.NSOpenPanel()
panel. beginSheetModalForWindow(self.view.window!.nsWindow!, completionHandler: { response in
    print(response)
})
```

**Comment by mhdhejazi** [comment]
I see.

The problem here is that `NSOpenPanel.beginSheetModalForWindow()` expects an Objective-C block, and we're passing a Switch closure which is entirely a different thing, and not interchangeable with Objective-C blocks.

From [docs](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Blocks/Articles/00_Introduction.html#//apple_ref/doc/uid/TP40007502-CH1-SW1):
> Block objects are a C-level syntactic and runtime feature.

And from [this post](https://academy.realm.io/posts/altconf-nikita-lutsenko-objc-swift-interoperability/):
>(...)  closures are a super-special case, like a custom type, built in Swift. Where in Objective-C, all of them are Objective-C objects. So to bridge Swift closure into Objective-C, Swift needs to create an Objective-C object for you

I can think of two options here:
1. Use `panel.runModal()`, and implement [`NSOpenSavePanelDelegate.validateURL`](https://developer.apple.com/documentation/appkit/nsopensavepaneldelegate/1535141-panel) to know when the user presses the "Open" button.
2. Create an Objective-C class that calls the method for you, and Swift will handle the bridging between ObjC blocks and Swift closures.

---

BTW, the extension can be re-written as following:
```swift
extension UIWindow {
    var nsWindow: NSObject? {
        Dynamic.NSApplication.sharedApplication.delegate.hostWindowForUIWindow(self)
    }
}
```

**Comment by mhdhejazi** [comment]
Good news! I found out a way to make Swift convert the closure to an Objective-C block.

You just need to add `@convention(block)` to the closure type:
```swift
typealias ResultBlock = @convention(block) (_ result: Int) -> Void
```

Now, this works flawlessly:
```swift
let panel = Dynamic.NSOpenPanel()
panel.beginSheetModalForWindow(self.view.window.nsWindow, completionHandler: { result in
    print("result: ", result)
} as ResultBlock)
```

**Comment by mhdhejazi** [comment]
I added a section about Objective-C blocks in the readme file. Thank you for bringing this to my attention!
